# Generated by Django 3.1.2 on 2020-11-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Videojuego', '0001_initial'),
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero_Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Video_Juegos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videojuego.videojuego')),
                ('ID_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Genero.genero')),
            ],
        ),
    ]
