# Generated by Django 3.1.2 on 2020-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('Placa', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Modelo', models.CharField(max_length=45)),
                ('Color', models.CharField(max_length=45)),
                ('Seguro', models.BooleanField()),
                ('Tecnomecanica', models.BooleanField()),
            ],
        ),
    ]
