# Generated by Django 3.1.2 on 2020-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=45)),
                ('Correo', models.CharField(max_length=45)),
                ('Contraseña', models.CharField(max_length=45)),
            ],
        ),
    ]
