# Generated by Django 3.1.2 on 2020-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('ID_Franquicia', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
    ]
